### ISSUE TITLE
GG STEAL CODE ARCTICUHC

### ISSUE THREAD

**Issue by LgRmael40** [Warvale/WarvaleUHC#1]
Remove this on github is fulll steal of ARCTICUHC or report

**Comment by RONTheCookie** [comment]
We'll discuss this with our developers.

**Comment by RONTheCookie** [comment]
Talked with our developers, they say nothing is stolen.

Feel free to DM me on discord: RONTheCookie#7386 if you have any other issues.

**Comment by LgRmael40** [comment]
Ok so if you do not remove this I will report a server concerned and moreover if you wanted it I would give you a good screen on the class and others.

**Comment by LgRmael40** [comment]
Your developer team is really pity nothing has been changed it's OMG copy

Logged in on eu.arcticmc.net

**Comment by LgRmael40** [comment]
And just do the command / uhc you have the same gui.

Anyway if you do not remove this from the github it will have consequance!

**Comment by LgRmael40** [comment]
http://www.noelshack.com/2017-38-2-1505829958-sans-titre.png

http://www.noelshack.com/2017-38-2-1505829905-sans-titre.png

**Comment by RONTheCookie** [comment]
If you have any real concerns shoot us a email over at **support@warvale.net** and we'll look further into it.
Please include proof that we copied it also.
